(defun count-spaces (&optional move-bolp)
  "Count empty whitespaces between start of line and first non
whitespace character."
  (interactive)
  (let ((count 0)
        (mark-bolp))
    (save-excursion
      (and move-bolp (move-beginning-of-line nil))
      (setq mark-bolp (point))
      (skip-chars-forward " \t")
      (or (eolp) (setq count (- (point) mark-bolp))))
    count))

(defun indent-non-rigidly (start end &optional amount)
  "Indent all lines in region relatively."
  (interactive "r\nP")
  (if (region-active-p)
      (let ((preindent 0)
            (width 0)
            (level 0)
            (ctr 0)
            (lines (count-lines start end)))
        (save-excursion
          (goto-char start)
          (setq preindent (count-spaces t))
          (while (and (= 0 width) (< (point) end))
            (forward-line)
            (forward-char preindent)
            (setq width (count-spaces)))
          (or amount (setq amount (+ 1 width)))
          (goto-char start)
          (while (< ctr lines)
            (forward-line)
            (forward-char preindent)
            (setq level (/ (count-spaces) width))
            (delete-char (* level width))
            (insert-char ?\ (* level amount))
            (move-end-of-line nil)
            (setq ctr (1+ ctr)))))
    (message "Please select an active region.")))
